### ISSUE TITLE
Design Family: Energy

### ISSUE THREAD

**Issue by cit1zen** [cit1zen/workers-and-resources-community-tech-tree#15]
- [x] Define streams for mechanical engineering family
- [x] Define technologies with names, descriptions, and relationships

**Comment by argentlike** [comment]
• Energy (fuel, power, )

**Comment by ryantheskinny** [comment]
I think this is a good chance to lock things like green energy (if someone makes a windmill or solar panels) and also better deisel generators that are more efficient/cleaner than like my small powerstation.

**Comment by argentlike** [comment]
agreed, we have environment under the health familiy right now.  this is a classic relationship mapping.    hmm - do we want environment under both energy and health as a stream? very different aspects.

btw I like your small power station - used it before.  I am using ryan's fuel one right now under HMC, and it is more costly (as is correct for fuel vs coal) xD

**Comment by argentlike** [comment]
Can we find out from Peter the likely direction of pollution? Health ye, but in terms of increased granularity f pollution types, effect, and spread?
