### ISSUE TITLE
Decide technologies should be part of 0.1.0

### ISSUE THREAD

**Issue by cit1zen** [cit1zen/workers-and-resources-community-tech-tree#8]
- [ ] Decide which technologies should be part of 0.1.0
- [x] Create a milestone for it
- [ ] Create issues for it

**Comment by argentlike** [comment]
Families first then.  Then we build the branches ( ) and interdependencies <>
•	Chemistry (chemicals, plastics)
•	Mechanical engineering (mech components, cars, ships, trains)
•	Electronics
•	Extraction (mines, oil wells)
•	Agriculture
•	Mass media
•	Health
•	Government
•	Energy
Becomes (DRAFT proposal)
•	Chemistry (chemicals, plastics, nuclear)
•	Mechanical engineering (mech components, cars, ships, trains, infrastructure)
•	Electronics
•	Primary Industries (mines, oil wells, agriculture, forestry)
•	Health (medicine/medical/sports)
•	Government (2x Secretariats:  Socialist Secretariat (treasury/economics/finance) Party Secretariat (control/propaganda/happiness/culture)
•	Energy
•	Mass media(do we need this separate?)

**Comment by cit1zen** [comment]
We will do the chemistry and mechanical engineering families for 0.1.0
