### ISSUE TITLE
Design Family:  Chemistry

### ISSUE THREAD

**Issue by argentlike** [cit1zen/workers-and-resources-community-tech-tree#9]
Determine the base 0.1.0 Technology Branches, their respective technologies and raise interdependencies with other Families and their Branches.

**Comment by argentlike** [comment]
Branches:
Organic (oil, gas)
Plastics ( )
Nuclear (isotopes, fission)

**Comment by cit1zen** [comment]
@argentlike Can you create a graph/list of technologies and relationships between them?

**Comment by argentlike** [comment]
![techtree overview 010 1](https://user-images.githubusercontent.com/62404441/77586272-00c63f00-6f3a-11ea-84f1-4625d0fdb743.jpg)

Overview Techtree Families

**Comment by argentlike** [comment]
So started some research today. Here is a snip which is probably easier for you.  I have made no attempt to sequence the categories, just what fits best where.
![Chemistry 010](https://user-images.githubusercontent.com/62404441/77610049-bb276780-6f75-11ea-9036-4290180111cd.jpg)

And when done we then 'test' it by adding assets as prerequisites or unlocks.  The prequisites can be categories and assets and this gives us a relationship mapping sequence for research.   We need also to consider do we want to tie time period (1960, 1968, 1970, etc)  locking against assets or categories, or both?
For our test.  We use some vanilla assets and some mods.  We select some including ones we think we want to create sequence mapping for in our developing 0.1.0 Families.
Are we going to get tied by hard coding from Peter?  Can we influence coding for relationships?  (I know you and Ryan have talked about some of this and he was going to raise a task/issue with Peter.)
Especially one to many and many to one mapping (you are the expert here, correct me).
I can shove some of the design on github later, but easier to explore here just a little for a lateral think... xD  The methodology development sequence and reflecting it in github is more your baby ?
A Note:  What we are doing is complex, but I think for the community modders, the instructions will be reasonably simple.

**Comment by cit1zen** [comment]
I would simplify the streams:
- Chemical Engineering can be just one stream with chemical factories
- Plastics can be just one stream with plastic factories that required lvl1 Chem Eng technology
- Petrochemical - Oil processing and Gas makes sense
- Nuclear - I would have only one stream here for nuclear fuel manufacture

**Comment by argentlike** [comment]
![chemistry v2](https://user-images.githubusercontent.com/62404441/77840949-6fc0c380-71d8-11ea-9bf6-8047fc8bcab1.jpg)

@cit1zen based on our chat, agreed?  I will then get mech engineering to same development - and then continue the background application guide.

**Comment by cit1zen** [comment]
@argentlike Yes, now it looks good and reasonable. Only thing that I would change is that I would remove food, water and sewage from the Chem Eng. They will probably appear somewhere else.

**Comment by cit1zen** [comment]
I am satisfied with the results of the design phase. I opened up an implementation task.
